import { assign, createMachine } from "xstate"

export const LOCALSTORAGE_KEY_AUTH = "phonebook-context-key"

export type PhoneBookEntry = {
  id: number
  firstName: string
  lastName: string
  phoneNumber: string
}

const phoneBookMachine = createMachine(
  {
    id: "phoneBook",
    // TypeScript types are generated by the XState VSCode extension:
    tsTypes: {} as import("./phoneBookMachine.typegen").Typegen0,
    schema: {
      // The context (extended state) of the finite state machine:
      context: {} as { phoneBookEntries: PhoneBookEntry[] },
      // The events handled by this fininte state machine:
      events: {} as  // CRUD operations + FINISH
        | { type: "CREATE"; phoneBookEntry: PhoneBookEntry }
        | {
            type: "READ"
          }
        | { type: "UPDATE"; phoneBookEntry: PhoneBookEntry }
        | { type: "DELETE"; phoneBookEntry: PhoneBookEntry }
        | {
            type: "FINISH"
          },
    },
    // We start in the "idle" state, which is where we should typically be:
    initial: "idle",
    // The initial context (initial state) of the state machine:
    context: {
      phoneBookEntries: [] as PhoneBookEntry[],
    },
    states: {
      idle: {
        on: {
          READ: {
            target: "ready",
            // Run these actions on state transition via trigger READ:
            actions: ["readPhoneBookFromLocalStorage"],
          },
        },
      },
      ready: {
        on: {
          CREATE: {
            target: "running",
            // Run these actions on state transition via trigger CREATE:
            actions: ["createPhoneBookEntry"],
          },
          UPDATE: {
            target: "running",
            // Run these actions on state transition via trigger UPDATE:
            actions: ["updatePhoneBookEntry"],
          },
          DELETE: {
            target: "running",
            // Run these actions on state transition via trigger DELETE:
            actions: ["deletePhoneBookEntry"],
          },
        },
      },
      running: {
        on: {
          FINISH: {
            target: "idle",
            // Run these actions on state transition via trigger FINISH:
            actions: ["writePhoneBookToLocalStorage"],
          },
        },
      },
    },
  },
  {
    actions: {
      readPhoneBookFromLocalStorage: assign({
        // We always have to include context and event, even when unused:
        phoneBookEntries: (context, event) => {
          const localStorageString = localStorage.getItem(LOCALSTORAGE_KEY_AUTH)
          if (localStorageString)
            try {
              const localStorageObject = JSON.parse(localStorageString)
              return localStorageObject as PhoneBookEntry[]
            } catch (error: any) {
              console.log(error) // Probably a JSON.parse error 😁
            }
          return [] as PhoneBookEntry[]
        },
      }),
      createPhoneBookEntry: assign({
        phoneBookEntries: (context, event) => {
          const currentPhoneBookEntries = context.phoneBookEntries
          const newPhoneBookEntry = event.phoneBookEntry
          currentPhoneBookEntries.push(newPhoneBookEntry)
          return currentPhoneBookEntries
        },
      }),
      updatePhoneBookEntry: assign({
        phoneBookEntries: (context, event) => {
          const currentPhoneBookEntries = context.phoneBookEntries
          const updatedPhoneBookEntry = event.phoneBookEntry
          const filteredPhoneBookEntries = currentPhoneBookEntries.filter(
            ({ id }) => id !== updatedPhoneBookEntry.id
          )
          filteredPhoneBookEntries.push(updatedPhoneBookEntry)
          return filteredPhoneBookEntries
        },
      }),
      deletePhoneBookEntry: assign({
        phoneBookEntries: (context, event) => {
          const currentPhoneBookEntries = context.phoneBookEntries
          const deletedPhoneBookEntry = event.phoneBookEntry
          const filteredPhoneBookEntries = currentPhoneBookEntries.filter(
            ({ id }) => id !== deletedPhoneBookEntry.id
          )
          return filteredPhoneBookEntries
        },
      }),
      writePhoneBookToLocalStorage: (context, event) => {
        try {
          localStorage.setItem(
            LOCALSTORAGE_KEY_AUTH,
            JSON.stringify(context.phoneBookEntries)
          )
        } catch (error: any) {
          console.log(error) // Something went horribly, horribly wrong. 🤯
        }
      },
    },
  }
)

export default phoneBookMachine
